### ISSUE TITLE
Discussion: Namespaced Gems?

### ISSUE THREAD

**Issue by mullermp** [rubygems/rfcs#31]
I wanted to open a discussion about supporting gem namespaces. Between this repo and the RubyGems.org repo, I wasn't sure where to start this discussion. If this was opened in the wrong place, I apologize, and feel free to close it.

Regarding the issue, though: currently, anyone can go and claim any gem they want, and it is difficult for organizations with a large number of gems (such as rails, aws, etc) to reserve rights to naming. It's not only confusing to customers, but can also be a concern for security if a malicious actor claims a similarly named gem and labels it as official. Other package managers (such as NPM's scopes) have support for namespaces.

My thoughts would be to use a `/` or `::` for namespacing, such as `gem install aws::s3` or `gem install rails/actionwhatever`

**Comment by mullermp** [comment]
I'm sorry for the radio silence on this issue. I've been caught up with other work related things. This is still a useful feature with large impact that I currently don't have the bandwidth to drive. If someone wants to own this, by all means please do.

**Comment by Fryguy** [comment]
@indirect What was the reason for closing?  Is it just because a formal RFC wasn't created yet?

**Comment by indirect** [comment]
This is a discussion ticket, and the discussion ended in March. What would the reason be for leaving this ticket open?

**Comment by mullermp** [comment]
Can we re-open the discussion in the ruby gem RFC repo? I haven't had time to write an actual RFC around this, but overall I think it's a useful feature/design/discussion to be having.

**Comment by mullermp** [comment]
Proposal is here: https://github.com/rubygems/rfcs/pull/40
